In [44]:
import numpy as np
import matplotlib.pyplot as plt

In [54]:
dataset = np.loadtxt("durudataset.txt")
dataset.shape

(40, 2)

In [55]:
def compute_distance(a, b):
    return np.linalg.norm(a - b)

In [137]:
pro = dataset[np.random.randint(0, m, size = 10)]
pro[2]

array([ 0.08488353,  0.20694325])

In [131]:
belongs = np.zeros((m, 1))
belongs[2]

array([ 0.])

In [ ]:
pro

In [142]:
def k_means(dataset, k, iteration = 10):
    m, n_features = dataset.shape
    history_centroids = []
    prototypes = dataset[np.random.randint(0, m, size = k)] # 随机选择k个中心
    history_centroids.append(prototypes) # 记录以往的所有中心
    prototypes_old = np.zeros(prototypes.shape)
    
    belongs = np.zeros((m, 1)) # 每个点属于哪一个clusters
    cost = 0 # 优化目标
    epoch = 0
    while epoch < iteration:
        epoch += 1
        for i in range(m):
            cost += compute_distance(dataset[i,:], prototypes[int(np.sum(belongs[i]))])
        cost /= m
        
        for index_instance, instance in enumerate(dataset):
            # 对于每一个样本
            distances = np.zeros((k, 1)) # 记录此样本到k个clusters的距离
            for index_prototype, prototype in enumerate(prototypes):
                distances[index_prototype] = compute_distance(prototype, instance)
            belongs[index_instance, 0] = np.argmin(distances)
        tmp_prototypes = np.zeros((k, n_features)) # 做交换用的中心储存器
        
        for index in range(k):
            # 计算离第index个中心最近的样本标记
            instacnes_closest = [i for i in range(len(belongs))if belongs[i] == index]
            # 计算新中心
            prototype_new = np.mean(dataset[instacnes_closest], axis = 0)
            tmp_prototypes[index, :] = prototype_new
            
        prototypes = tmp_prototypes
        
        history_centroids.append(tmp_prototypes)
        
        print("The cost is %f" % cost)
        
    return prototypes, history_centroids, belongs

In [144]:
prototypes, history_centroids, belongs = k_means(dataset,k = 3, iteration = 10)

The cost is 1.334783
The cost is 0.262290
The cost is 0.231731
The cost is 0.227632
The cost is 0.224172
The cost is 0.221251
The cost is 0.221178
The cost is 0.221176
The cost is 0.221176
The cost is 0.221176


In [145]:
prototypes

array([[ 1.87372935,  1.76339973],
       [ 0.22331067,  0.28960446],
       [ 1.38515121,  1.43935704]])

In [146]:
belongs.T

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  0.,  2.,  2.,  2.,  0.,
         2.,  2.,  0.,  2.,  0.,  0.,  2.,  2.,  2.,  2.,  0.,  0.,  0.,
         2.]])